# Apêndice

## Códigos utilizados para análise das bases de dados

### Produto 2

1. [Scripts de análise de dados feitos em R](https://github.com/abjur/cnjML).
1. [Scripts para arrumar dados dos tribunais](https://github.com/abjur/tidyML).
1. [Scripts para arrumar nomes das empresas](https://github.com/abjur/tidyPJ).
1. [Pacote em R utilizado para armazenas as TPUs do CNJ](https://github.com/abjur/tpur).
1. [Pacote em R utilizado para criar a *whitelist* do TJSP e estimar volumes processuais](https://github.com/abjur/tpur).
1. [Scripts de web scraping de tribunais do sistema SAJ](https://github.com/courtsbr/esaj).
1. [Scripts de web scraping de diversas páginas do TJSP](https://github.com/courtsbr/tjsp).
1. [Modelos para quebrar CAPTCHAs](https://github.com/decryptr/).

### Estudo sobre teses da USP

1. [Pacote em R utilizado para download dos acórdãos](https://github.com/abjur/esaj).
1. [Base de dados sobre acórdãos utilizada](https://www.dropbox.com/s/kkqlghd5cv10u99/d_ementas_2014.rda?dl=0).
1. [Pacote em R utilizado para download das teses da USP](https://github.com/abjur/teses.usp).
1. [Base de dados de teses da USP](https://github.com/jtrecenti/teses.usp/raw/master/data/teses_usp.rda).


## Eixos de investigação cortados no decorrer da pesquisa

Os seguintes eixos de investigação foram deixados de lado no decorrer da pesquisa por serem muito complexos de executar e/ou por apresentarem pouco potencial de resolver problemas de administração judiciária. Ainda assim, optamos por manter os eixos, pois outros pesquisadores podem enxergar oportunidades não identificadas pela ABJ durante a execução do projeto.

### Incidentes de demandas repetitivas

Outra importante ferramenta instituída pelo novo CPC para redução dos
processos em trâmite no Poder Judiciário é o Incidente de Resolução de
Demandas Repetitivas (IRDR), cujo procedimento é regulado pelo artigo
976 e seguintes do novo diploma processual.

O IRDR é cabível quando houver, simultaneamente, duas condições: i)
efetiva repetição de processos que contenham controvérsia sobre a mesma
questão unicamente de direito, tanto material quanto processual; e ii)
risco de ofensa à isonomia e à segurança jurídica.

Isso significa que deve haver aspectos fáticos repetitivos nos diversos
casos analisados. Como, por exemplo, em casos nos quais as partes tenham
realizado o mesmo tipo de atividade negocial e agora discutem com o
Fisco a incidência de Imposto, ou nos quais as partes pretendem a
devolução de valores em razão de planos econômicos instituídos pelo país
no início dos anos 1990.

A instauração do incidente pode ser pedida pelo juiz ou relator, pelas
partes da demanda, pela Defensoria Publíca ou Ministério Público. Quando
o Ministério Público não pedir a instauração do incidente, deverá
funcionar como fiscal da Lei.

O IRDR é julgado pelo órgão do tribunal responsável pela uniformização
da jurisprudência. Admitido o incidente pelo relator, os processos
classificados no grupo correspondente são suspensos. Uma vez julgado o
incidente, a tese jurídica será aplicada conforme o art. 985, I e II:


> "I - a todos os processos individuais ou coletivos que versem sobre
> idêntica questão de direito e que tramitem na área de jurisdição do
> respectivo tribunal, inclusive àqueles que tramitem nos juizados
> especiais do respectivo Estado ou região; II - aos casos futuros que
> versem idêntica questão de direito e que venham a tramitar no território
> de competência do tribunal, salvo revisão na forma do art. 986".

Do julgamento do mérito do incidente caberá recurso extraordinário ou
especial. O recurso tem efeito suspensivo e a repercussão geral do
recurso extraordinário será presumida. A tese jurídica adotada pelo
Supremo Tribunal Federal (STF) ou pelo Superior Tribunal de Justiça
(STJ) será aplicada no território nacional a todos os processos
individuais ou coletivos que versem sobre idêntica questão de direito.

Por se tratar de um instituto inédito e com pouco tempo de vigência, o
IRDR tem sido pouco utilizado. Pela dificuldade em se identificar o que
deve ser considerado como "questão unicamente de direito", é incerto o
efeito de tais medidas.

A única hipótese em relação ao IRDR é que, pelo fato deste tratar de
questões unicamente de direito, este dispositivo do CPC não influencia
os processos que envolvem direito do consumidor de forma significativa.
A hipótese será avaliada a partir de um conjunto de suposições bem
definidas e um modelo de simulação.

O IRDR era um tema potencialmente interessante no início da pesquisa.
Estudar sua aplicação é uma forma de avaliar os impactos do novo CPC no
direito do consumidor. Soluções envolvendo o IRDR também poderiam ajudar
a decidir processos em bloco sem reduzir a segurança jurídica, aumentando
significativamente a eficiência dos tribunais.

Infelizmente, em todas as entrevistas o tema ficou em segundo plano. É
grande a descrença em aplicações práticas do IRDR. E é pequena a fatia
dos problemas do consumidor que ele ataca. Para ser efetivo, o IRDR
precisaria de uma tecnologia de identificação e agrupamento de processos
que ainda não existe em nenhum tribunal. Além disso, existem poucos
casos disponíveis para análise.

Concluímos que o IRDR precisa de tempo para maturar e tornar-se passivo
de análise quantitativa. Por isso, o eixo de investigação foi descartado
na presente pesquisa.

### Otimização da fila de trabalho

A redação original do art. 12 do novo CPC previa, de maneira sucinta,
que os juízes e os tribunais deveriam observar a ordem cronológica de
conclusão para proferir sentenças e acórdãos. No mesmo sentido, a
redação original do art. 153 determinava que o escrivão ou chefe de
secretaria observasse a ordem cronológica de recebimento para publicação
e efetivação dos pronunciamentos judiciais.

Sensível aos problemas que essa determinação poderia trazer para o
funcionamento das varas judiciais e tribunais, o legislador editou a Lei
n.º 13.256/2016, que acrescentou a palavra ``preferencialmente'' aos
artigos 12, Caput, e 153 do CPC:


> "Art. 12. Os juízes e os tribunais atenderão, preferencialmente, à
> ordem cronológica de conclusão para proferir sentença ou acórdão."
> 
> "Art. 153. O escrivão ou o chefe de secretaria atenderá,
> preferencialmente, à ordem cronológica de recebimento para publicação e
> efetivação dos pronunciamentos judiciais."

A partir das modificações perpetradas pela Lei n.º 13.256/2016, os
magistrados, escrivães ou chefes de secretaria não mais estão obrigados
a observar a ordem cronológica de tramitação dos processos. Por isso,
foram estabelecidas exceções à essa regra no parágrafo 2º do
dispositivo.

Dessa forma, tem-se o seguinte:

- O magistrado não está obrigado a seguir a ordem cronológica dos
  processos para proferir sentença ou acórdão, devendo segui-la
  preferencialmente, desde que possível.
- Há exceções legais que determinam que um processo seja julgado antes
  de outros, independentemente de sua ordem cronológica.

A liberdade na forma de atuação do juiz nesse sentido pode ser vista
como positiva, pois dessa forma é possível delimitar a ordem que melhor
atenda às necessidades de cada vara. Na prática, no entanto, isso
implica na descentralização da administração das varas, em que cada juiz
administra o cartório de forma arbitrária. Esse problema, somado à
conhecida falta de mecanismos de comunicação entre os juízes, gera uma
sensação de caos na administração da justiça.

Uma forma possível de solucionar esse problema seria através da
otimização da fila de trabalho dentro do cartório. Isso seria realizado
através de um modelo que ordenaria os trabalhos a serem realizados em
cada dia, considerando todos os agentes do cartório.

A hipótese para esse tema é a de que existem formas de ordenar as
tarefas dentro de um cartório capaz de i) minimizar o número de ações a
serem tomadas, através de ações e blocos de processos, ii) reduzir o
tempo médio entre a distribuição e a sentença do processo e iii) manter
constante ou reduzir a taxa de recorribilidade.

Os resultados para esse tema são simulações,
baseadas em dados reais de movimentações processuais e utilização de
modelos similares aos descritos em @Fossaluza2015. A mensuração da
importância envolve, entre outras características, a complexidade
processual. Portanto, a implementação deve levar em conta métodos para
mensuração de complexidade.

A ideia de otimizar filas de trabalho já nasceu problemática. O tema
surgiu de dentro do Laboratório de Jurimetria e baseia-se na suposição
de que a ordenação de tarefas dentro de uma vara é ineficiente. Um
algoritmo de otimização poderia ser usado para agrupar processos
similares ou tarefas repetidas dentro de processos distintos, eliminando
retrabalho da vara.

Nas entrevistas, observamos que o tribunal já possui
diversos modelos de documentos e ritos bem definidos. Novos padrões para
fluxo de trabalho das varas seria útil apenas em comarcas com menor
volume processual. A solução também apresenta dificuldades de
implementação, pois precisa ser integrado aos sistemas existentes e
poderiam exigir treinamento.

### Incentivos para litigar

Segundo @CNJ2015, os processos mais recorrentes do direito do
consumidor são os que envolvem danos morais, sendo este um
assunto processual que tem a intuição de estar associado a uma
"indústria". Esse fato poderia ser explicado por conta de juízes que arbitram valores de indenização altos o suficiente, instigando pessoas a litigar. Em outras ocasiões, é possível ajuizar litígios que desfavorecem a requerida em prol da requerente, além do simples intuito de indenizar um dano sofrido.

Esse é argumento particularmente plausível no caso dos JECs, por conta
da inexistência das custas processuais e sucumbência [@Athos2015].
Se desconsiderarmos o custo de litigar por conta do tempo dispendido
para iniciar e acompanhar a ação, mesmo quando a probabilidade de
sucesso é baixa, litigar é um ato vantajoso para o autor, mesmo que este
não tenha razão.

Outro tópico relevante nesse contexto é a gratuidade judiciária, que tem
fundamento no princípio constitucional da inafastabilidade do poder
judiciário (CF, art. 5º, XXXV). A gratuidade também se encontra guarida
na oferta constitucional de assistência judiciária integral e gratuita
àqueles que comprovarem insuficiência de recursos (CF, art. 5º, LXXIV).

O novo CPC derrogou (revogou parcialmente) as disposições da Lei
1.060/1950 e passou a também regular a gratuidade da justiça, que
compreende: i) taxas e custas judiciais; ii) selos postais; iii)
despesas com publicações na imprensa oficial; iv) indenização devida à
testemunha pelo dia não trabalhado; v) despesas com realizações de
exames de DNA e outros considerados essenciais; vi) honorários de
advogados, peritos, remuneração do intérprete ou tradutor; vii) custas
para elaboração de memórias de cálculo, quando exigidas; viii) depósitos
para interposição de recursos, propositura de ação e prática de outros
atos inerentes ao exercício do contraditório e da ampla defesa; ix)
emolumentos devidos a notários ou registradores necessários para
efetivação de decisão judicial ou regular processamento da demanda
(CPC/2015, art. 98, § 1º).

A concessão da gratuidade da justiça não afasta a responsabilidade do
beneficiário pelas despesas processuais e pelos honorários advocatícios
decorrentes de sua sucumbência. Nesse caso, as obrigações do
beneficiário ficarão sob condição suspensiva de exigibilidade e somente
poderão ser executadas se, nos 5 anos subsequentes ao trânsito em
julgado da decisão que as certificou, o credor demonstrar que deixou de
existir a situação de insuficiência do beneficiário.

O momento de concessão da gratuidade da justiça, que pode ocorrer em
relação a algum ou a todos os atos processuais, e que pode consistir na
redução percentual dos valores é regulado pelo art. 99 do novo CPC.

O dispositivo supramencionado prevê, em seu *Caput*, que a
gratuidade pode ser pedida na petição inicial, na contestação, na
petição para ingresso do terceiro ou em recurso. Mas também pode ser
requerida em momento ulterior, por simples petição, desde que a condição
de insuficiência seja superveniente à primeira manifestação da parte. Na
prática, a justiça gratuita pode ser pedida em qualquer momento do
processo.

A possibilidade de o magistrado indeferir o pedido de justiça gratuita,
tema que é o cerne deste tópico, também é tratada no art. 99 do novo
CPC. Trata-se de questão sensível.

O § 3º do art. 99 determina que "presume-se verdadeira a alegação de
insuficiência deduzida exclusivamente por pessoa natural". Por sua vez,
o art. 99, §2º, prevê que o magistrado somente poderá indeferir o pedido
se houver nos autos elementos que evidenciem a falta dos pressupostos
para a concessão de gratuidade. E antes de indeferir o pedido, o
magistrado deve possibilitar que a parte comprove o preenchimento dos
requisitos.

Dessa forma, a balança pende para o lado da concessão da justiça
gratuita para as pessoas naturais, na medida em que: i) há uma presunção
de insuficiência por mera declaração; ii) essa presunção somente pode
ser afastada caso o magistrado verifique a existência de elementos que
demonstrem que o réu não possui insuficiência, o que normalmente ocorre
apenas naqueles casos extremos; iii) ainda que o magistrado afaste a
presunção, deve dar à parte a possibilidade de provar que preenche os
requisitos de insuficiência.

Na prática, o que ocorre é que grande parte dos magistrados concedem a
justiça gratuita sem maiores reflexões ou averiguações, exceto quando a
situação de riqueza da parte é muito evidente. Se aceita, a gratuidade
judiciária implica em incentivos similares para litigar quando
comparados aos JECs.

Por outro lado, também precisamos considerar o acesso à justiça para
equacionar os incentivos para litigar de forma adequada. Note que, se
colocarmos um custo de litigar altíssimo, teríamos um judiciário livre
de ações, mas uma sociedade sem acesso à justiça. Mas, se colocarmos um
custo de litigar igual à zero, teríamos amplo acesso à justiça, mas uma
baixa qualidade na prestação jurisdicional.

Também podemos considerar que o custo de litigar varia conforme o poder
econômico do consumidor. Com efeito, duas pessoas envolvidas em
conflitos similares, mas com poderes aquisitivos distintos possuem
incentivos diferentes para entrar com ações judiciais.

Portanto, o fenômeno da litigiosidade em ações consumeristas por parte
do consumidor pode ser estudado a partir de um modelo econométrico que
busca maximizar a eficiência do judiciário. Esse tópico é amplamente
estudado por uma área da jurimetria denominada "viés de seleção em
decisões judiciais" [@priest1984selection].

As hipóteses sobre esse tema são:

1. A inexistência de custas processuais e sucumbência na primeira
  instância dos JECs impacta positivamente na entrada de ações
  consumeristas.
1. A legislação atual sobre gratuidade judiciária impacta positivamente
  na entrada de ações consumeristas.

Os resultados dessa pesquisa podem influenciar proposições tais como:

1. Metodologias concretas de mensuração do acesso à justiça, com base em
  suposições e critérios bem definidos.
1. Alterações na legislação para inclusão de valores ótimos de
  sucumbência e/ou custas processuais, buscando balancear o acesso à
  justiça e a prestação jurisdicional eficiente.

Juízes e empresários têm diferentes hipóteses sobre o valor da taxa de conversão de conflitos em litígios relacionados ao consumidor, o que leva a
diferentes percepções sobre a influência de fenômenos como a gratuidade
judiciária, as custas processuais nos JECs e a indústria do dano moral
no volume de ações.


### Motivações para o cometimento de ilícitos

Neste eixo de investigação temos interesse em estudar as causas de
litigar associadas às empresas. Em particular, desejamos compreender as
motivações por trás do cometimento de ilícitos.

A motivação por trás da elaboração deste eixo reside na suposição de que
uma empresa funciona como agente racional e maximizador de lucro. Dessa
suposição seguem as hipóteses:

1. Se, para uma determinada empresa, o custo associado a administração de
  um litígio for menor que o custo empregado para evitar um ato ilícito,
  então a decisão escolhida pela empresa será cometer o ilícito.
1. Uma redução no número de atos ilícitos cometidos acarreta uma
  diminuição do número de litígios.

Utilizando as duas hipóteses, concluímos que se for economicamente
viável pra uma empresa cometer um ato ilícito, então o número de
litígios aumentará. Por outro lado, neste cenário é possível mitigar os
riscos de ilicitudes tornando economicamente inviável o cometimento de
uma infração através de multas ou sanções.

Com esse raciocínio em mente, nossas investigações se concentrarão em
aproximar as condições de contorno à tomada de decisões jurídicas da
administração de uma empresa. Assim, verificaremos se existem meios para
desincentivar o cometimento de atos ilícitos em instituições para as
quais vale a hipótese 1.

Como possíveis resultados, temos a elaboração de propostas para leis,
multas ou sanções que tornem economicamente inviável o cometimento
frequente de ilícitos. Esses dispositivos podem ser operacionalizados em
função do valor médio de indenização ou dano médio causado ao
consumidor.

Esse tema dividiu opiniões nas reuniões.
O cometimento de ilícitos é o insumo dos conflitos entre
empresa e consumidor. Na analogia da torneira, entender as motivações
para o cometimento de ilícitos é o mesmo que estudar o encanamento por
trás da torneira. Infelizmente, não é possível quebrar a parede para
analisar o encanamento -- não podemos investigar nem relatar
publicamente as políticas internas dos maiores litigantes em ações
consumeristas.

As análises para o tema ficariam apenas no plano teórico e os modelos
finais poderiam ser aplicadas no mundo real somente após a coleta de
novos dados. Por isso, resolvemos deixar as análises em segundo plano,
possivelmente em pesquisas futuras.

### Estratégias de composição amigável

As duas maiores inovações do novo CPC são i) a ênfase atribuída ao dever
de cooperação entre as partes e ii) as aberturas para atuação dos
chamados meios alternativos de solução de litígios.

Dentro do âmbito desta última, encontram-se as estratégias de
conciliação e mediação. Dois pontos são relevantes para compreender como
as estratégias de conciliação e mediação podem ajudar na redução do
número de processos que estão em trâmite perante o Poder Judiciário: a
obrigatoriedade da conciliação ou mediação e as semanas nacionais de
conciliação.

**Obrigatoriedade do procedimento arbitral**. Tendo por objetivo
fomentar a composição amigável, o novo CPC inovou e estabeleceu que os
Tribunais deverão criar centros judiciários de solução consensual de
conflitos através do art. 165:

> "Art. 165. Os tribunais criarão centros judiciários de solução
> consensual de conflitos, responsáveis pela realização de sessões e
> audiências de conciliação e mediação e pelo desenvolvimento de programas
> destinados a auxiliar, orientar e estimular a autocomposição".

Dessa forma foi instituída a figura do conciliador, que atuará
preferencialmente em casos em que não houver vínculo anterior entre as
partes, e do mediador, que atuará preferencialmente em casos em que
houver vínculo anterior entre as partes. A atuação do conciliador ou do
mediador é obrigatória sempre que houver conciliador ou mediador na
comarca na qual se instaurou a situação litigiosa.

Por sua vez, o CPC estabelece que após verificar que a petição inicial
preenche os requisitos essenciais e não é o caso de improcedência
liminar do pedido, o juiz designará audiência de conciliação ou de
mediação. Em outras palavras, a designação da audiência é obrigatória e
deverá ser designada com no mínimo 30 dias de antecedência, devendo o
réu ser citado com 20 dias de antecedência, como estabelece o art. 334:

> "Art. 334. Se a petição inicial preencher os requisitos essenciais e
> não for o caso de improcedência liminar do pedido, o juiz designará
> audiência de conciliação ou de mediação com antecedência mínima de 30
> (trinta) dias, devendo ser citado o réu com pelo menos 20 (vinte) dias
> de antecedência."

Em apenas duas hipóteses a audiência de conciliação ou mediação não é
obrigatória. A primeira é quando as partes manifestam expressamente seu
desinteresse na realização da audiência - o autor na petição inicial e
os réus em até 10 dias antes da realização da audiência. A segunda é
quando o direito que estiver em disputa não admitir autocomposição.

Visando garantir efetividade aos mecanismos de autocomposição, o CPC
previu: i) meios para facilitar sua realização (que poderá ser feita por
meio eletrônico); ii) meios para aumentar sua celeridade (realização de
segunda audiência, desde que necessária à composição, em não mais do que
2 meses após a primeira); e iii) imposição de multa para a ausência
injustificada das partes (de até 2% sobre o valor da vantagem econômica
almejada ou sobre o valor da causa).

Não obstante a preocupação do legislador em fomentar a autocomposição e
desafogar o Poder Judiciário, é possível verificar que, na prática,
muitos Juízes têm deixado de designar a audiência de conciliação ou
mediação em razão de falta de pauta para sua realização.

Uma das soluções possíveis para esse impasse é investir no cadastramento
e treinamento dos mediadores e conciliadores. Na medida em que os
mediadores e conciliadores são os responsáveis por dirigir as audiências
de composição, o aumento do seu número poderá levar a uma ampliação das
composições amigáveis, sem que isso implique em uma maior quantidade de
trabalho para os magistrados.

**Semana de Conciliação**. O CNJ promove anualmente a Semana
Nacional da Conciliação. Trata-se de uma campanha de mobilização na qual
todos os Tribunais Brasileiros concentram seus esforços, durante uma
semana, na obtenção do maior número possível de composições amigáveis.

Durante a preparação para a Semana Nacional da Conciliação, os Tribunais
escolhem quais processos judiciais são passíveis de serem apresentados
em audiência de conciliação. Na sequência, comunicam formalmente as
partes litigantes. Caso uma das partes que não teve seu caso relacionado
também queira resolvê-lo durante o mutirão, ela pode procurar o Tribunal
em que o caso estiver tramitando, desde que com antecedência.

A Semana Nacional de Conciliação é orientada pela Resolução nº 125 do
CNJ, que dispõe sobre a "Política Judiciária Nacional de tratamento
adequado dos conflitos de interesses no âmbito do Poder Judiciário" e
traz entre os seus princípios fundamentais: informalidade, simplicidade,
economia processual, celeridade, oralidade e flexibilidade processual.
Inspirada na Semana Nacional de Conciliação promovida pelo CNJ, diversos
Tribunais estaduais têm promovido semanas estaduais de conciliação.

Diante do exposto, temos as seguintes hipóteses sobre o fenômeno da
conciliação:

- A obrigatoriedade da audiência de conciliação não aumenta a
  probabilidade de acordo de um processo em relação à probabilidade de
  acordo de processos do mesmo tipo com audiência não obrigatória.
- Processos escolhidos para a semana de conciliação possuem
  probabilidade maior de acordo do que processos do mesmo tipo que não
  foram escolhidos.

O resultado dessa análise poderá implicar em propostas como:

- Modificar o art. 165 do CPC para sinalizar a audiência de conciliação
  somente em processos pré-classificados como mais suscetíveis à
  realização de acordo. A suscetibilidade ao acordo pode ser definida
  através de um modelo preditivo da probabilidade de acordo de
  processos.
- Planejar a realização de semanas de conciliação de forma mais
  sistemática, para funcionarem como experimentos controlados, o que
  permitirá mensurações mais precisas do efeito da conciliação.
- Promover eventos de conciliação para processos envolvendo relações de
  consumo de determinados tipos, épocas do ano e regiões.

A conciliação é um tema amplamente discutido no judiciário e aparece
como prioridade na pesquisa. No entanto, nas reuniões, vimos que o
interesse não é tão grande para ações envolvendo direito do consumidor.
Os especialistas acreditam que a proporção de processos com composições
amigáveis está próxima do máximo alcançável; nos casos restantes, alguma
das partes realmente não tem interesse no acordo. Isso significa que
criar mais formas de incentivar o acordo não têm resultado prático.

No final, acabamos não utilizando dados para realizar análises sobre conciliação. Essa parte da pesquisa foi transferida para pesquisas futuras, especialmente nas pesquisas locais.

A única proposta levantada sobre esse eixo foi a realização de experimentos controlados com a utilização da semana de conciliação. A condução de estudos desse tipo trará maior conhecimento sobre o que explica o fenômeno do acordo e quais os meios de fazê-lo acontecer com maior frequência.

## Questionário

As entrevistas partiram de um conjunto bem definido de perguntas, mas
não tem um limite para os tipos de discussão realizadas, desde que não
fujam do tema da pesquisa. As perguntas levantadas foram listadas
abaixo.

1. Gasto Jurídico.
    1. Qual a proporção entre os gastos jurídicos consumeristas e os demais
    gastos jurídicos? Esta proporção é comparável à existente no resto
    do mundo?
    1. Qual a proporção entre os gastos jurídicos consumeristas e os demais
    gastos da empresa? Esta proporção é comparável à existente no resto
    do mundo?
    1. Quanto o preço de um produto é aumentado, em média, devido a gastos
    jurídicos?
1. Tipo de litígio.
    1. Quais os principais litígios ajuizados contra a empresa em relação a: i) matéria e ii) tipo processual.
    1. Qual a duração média dos litígios?
    1. Efeito de sites como "Reclame Aqui" sobre a litigiosidade?
    1. Quão frequentes são litisconsórcios passivos e ações coletivas? Poderiam ser usados mais vezes?
1. Estratégia processual.
    1. Como os processos são divididos entre escritórios? (Supondo haver
    mais de um), como os advogados que lidam com a causa lidam com o
    elevado número de casos? (recursos computacionais? bancos de dados?
    terceirização de serviços? outros?)
    1. Adotam estratégias para chegar a acordos/mediação? Sob quais
    circunstâncias? Quais? Sob quais circunstâncias tenta-se negociar
    com o consumidor para evitar a ação judiciária? Algum dos
    profissionais responsáveis pelo atendimento ao cliente tem
    especialização em mediação? Ela é incentivada pela empresa? Em
    geral, consumidores buscam uma solução pacífica antes de buscar o
    judiciário?
    1. Comportamento da empresa mudou em função de decisões no judiciário?
    Existem decisões do judiciário que a empresa acredita serem
    prejudiciais à Sociedade?
    1. Comportamento da empresa mudou em função das agências reguladoras? A
    empresa vê que elas cumprem bem sua finalidade?
    1. Sob quais circunstâncias a empresa recorre de uma decisão? (1a e 2a
    instância?)
    1. De que forma danos morais são tratados na justiça consumerista?
1. Legislação consumerista.
    1. Qual a opinião da entidade/profissional sobre a legislação
    consumerista?
    1. Há pontos que incentivam demasiadamente a litigiosidade?
    1. Há pontos que trazem custos demasiados à empresa?
    1. Há pontos da legislação que poderiam ser melhorados?
    1. Existem leis que são propositadamente infringidas pelas empresas por
    serem economicamente inviáveis? (ou respeitá-las seria economicamente ineficiente).
1. Agências reguladoras
    1. Qual a relação da empresa com as agências reguladoras?

## Anotações das reuniões

As anotações abaixo foram realizadas informalmente e sem instrumentos apropriados para coleta. As anotações não refletem nem a opinião da ABJ nem a opinião dos entrevistados sobre o tema, e não devem ser utilizados para inferências sobre opiniões das empresas, de advogados ou dos Tribunais de Justiça.

As anotações não refletem diretamente a opinião dos especialistas e sim as anotações da ABJ.

A primeira reunião contou com a presença dos advogados Rodrigo Araújo e
João Braz e teve como principais resultados as anotações abaixo.

1. A obrigatoriedade da realização de audiências de conciliação prévias
   (CPC/2015, art. 334, Caput) pode influenciar de forma negativa no
   andamento dos processos.
1. O novo CPC estabeleceu que os Tribunais deverão criar centros
  judiciários de solução consensual de conflitos (CPC/2015, art. 165,
  Caput), o que pode ter efeito positivo sobre o volume de ações do
  consumidor.
1. Os IRDR só terão efeito sobre matérias de direito e não em matérias de
  fato. Além disso, supõe-se que a maior parte dos processos envolvendo
  direito do consumidor envolvem prioritariamente questões de fato.
  Assim, espera-se que o IRDR não tenha efeito positivo para resolução
  de demandas do consumidor.

A segunda reunião contou com a presença de Armando Rovai, presidente da SENACON.

1. O superendividamento é um problema corrente nos canais do portal
  Consumidor.gov. É possível afirmar que o consumidor não é o único
  responsável pelo endividamento, uma vez que este pode ser mitigado por
  bancos e fornecedores de cartões de crédito que possuam informações
  aprofundadas do consumidor.
1. Planos de saúde. Considerando o maior acesso a planos de saúde pela
  população em geral e o aumento recente de ações de erro médico, uma
  possível hipótese é que as seguradoras não estão preparadas para
  atender de forma adequada a demanda dos novos clientes. Isso indica a
  necessidade de criação de programas para reunir essas instituições e
  debater sobre as causas raiz dos processos judiciais.
1. A SENACON tem o interesse de medir o impacto das políticas da própria
  entidade. A metodologia usada para mensuração desses impactos poderiam
  ser extrapoladas para outras entidades.

O terceiro grupo focal contou com a presença de Maria Rita Rebello e Ana
Rita Nery, ambas juízas assessoras da corregedoria.

1. Sobre ações coletivas
  - Ações coletivas são uma solução melhor que IRDR, pois o IRDR ainda
    mantém a necessidade de sentenças individuais.
  - Como implementar ações coletivas de forma mais sistemática: criar um
    dashboard para o Ministério Público (MP) que monitore dados dos
    canais Procon, Reclame Aqui, Consumidor.gov e Judiciário e
    identifique movimentações anômalas de grupos de processos em
    determinados lugares ou tempos, para indicar a necessidade de criar
    ações coletivas.
  - Faz sentido entrevistar o MP para falar sobre ações coletivas.
1. Sobre conciliação
    - A conciliação não é uma forma de melhorar o judiciário em ações
    consumeristas.
    - A conciliação faz mais sentido quando a relação é entre
    pessoa/pessoa. Quando a relação é entre pessoa/empresa, a pessoa só
    entra com a ação se realmente não tem mais como resolver a situação
    de outra forma. A probabilidade de aceite de acordo dado que o
    processo envolve relação de consumo é baixa.
  - A obrigatoriedade da conciliação é inconstitucional.
  - Incentivar fortemente a conciliação pode ser visto como mais uma
    forma de incentivar a empresa a cometer ilícitos.
1. Sobre fila de trabalho nos processos
  - Não aumenta a velocidade dos processos no TJSP, pois o tribunal já
    possui diversos modelos de documentos e ritos bem definidos. O novo
    CPC também ajuda nesse sentido.
  - O foco deve ser em métodos para identificação de boas práticas na
    administração de varas e bases de conhecimento internas para
    facilitar comunicação (e.g.\textasciitilde{}informar sobre um
    advogado que frauda documentos, criar fluxos de atuação do juiz em
    certos tipos de casos etc.)
  - Em comarcas menores e tribunais com sistemas mais precários, faz
    sentido implementar técnicas de filas de trabalho, pois os juízes
    desses lugares não administram a vara de forma eficaz.
1.  Sobre incentivos para litigar
    - Não existem tantos incentivos para litigar por parte das pessoas.
    - É pequeno número de pessoas que entra com ações, comparado com o
    volume de conflitos que não são resolvidos extrajudicialmente.
    - Uma taxa baixa de conversão de conflitos em litígios é benéfica para
    a empresa.
1. Sobre incentivos das empresas para cometerem ilícitos
  - É o grande gargalo na questão dos incentivos para litigar.
  - Uma possível solução é a implementação de \emph{punitive damages}.
  - As sanções e multas de agências reguladoras podem funcionar como
    substitutas para \emph{punitive damages}, mas as agências não têm
    interesse em aplicá-las.
  - O ideal seria vincular uma estratégia de sanções ao Procon.
1. Mecanismos de composição extrajudicial
  - Ferramentas como Reclame Aqui e Consumidor.gov são indispensáveis.
  - O SAC não é um bom mecanismo pois as empresas não têm interesse que
    elas sejam eficazes.

A quarta reunião contou com a presença da diretoria de contencioso cível do Itaú-Unibanco.

1. Sobre ações coletivas e IRDR
  - O IRDR não funciona pois os juízes não seguirão as regras de demandas repetitivas.
  - Não houve comentários sobre ações coletivas
1. Sobre conciliação
  - Composição extrajudicial é mais eficiente do que acordo dentro do
    processo.
  - Aumentar incentivos para o acordo dentro do judiciário não aumenta a
    proporção de acordos.
1. Sobre incentivos para litigar
  - Existe incentivo para litigar. Quando a pessoa se sente injustiçada,
    entra no judiciário mesmo com propostas de composição extrajudicial.
  - Existem incentivos macroeconômicos para litigar. Crise gera
    inadimplência, que gera aversão a cobranças, que gera ações para
    negar relação contratual (e.g.~tarifas bancárias).
  - Existe indústria do dano moral, mas só em alguns lugares e para
    alguns juízes. O efeito é pontual.
  - Gratuidade judiciária deveria ser baseada em critérios objetivos.
  - JEC também tem o mesmo problema. As pessoas têm incentivo a litigar
    e com os maiores valores possíveis.
1. Incentivos das empresas para cometerem ilícitos
    - Existem empresas que maximizam lucro colocando na conta a perda
    esperada por indenização.
  - Esse tipo de atitude é mais comum em empresas menores, que ainda não
    implantaram governança corporativa.
  - Atualmente os grandes bancos não fazem isso e tentam evitar os
    conflitos ao máximo.
1. Mecanismos de composição extrajudicial
  - Extremamente importante e subutilizado.
  - Há necessidade de incentivar as pessoas a procurarem mais esses
    meios.
  - Na maioria dos casos as pessoas não procuram meios extrajudiciais
    para solução de conflitos
  - Isso também está ligado à cultura do litígio na advocacia. Advogados
    (ruins) têm de tudo para cooptarem clientes e entrarem com ações de
    consumo. A concentração de ações esteja em escritórios pequenos ou
    advogados que atuam sozinhos. Isso é influência de i) excesso de
    advogados no país e ii) faculdades ruins.
  - A OAB não tem interesse em reduzir litigiosidade, por isso ela foca
    em temas como conciliação e IRDR e acesso à justiça, e fogem de
    alternativas extrajudiciais ou de mudança de cultura dos advogados.
  - Existe uma associação entre taxa de estudantes de direito de um
    determinado município (por habitante) e a taxa de ações envolvendo
    direito do consumidor (por habitante).
  - Proposta de criação de regra de conduta para juízes: se uma pessoa
    entra com processo sem ter procurado mecanismos como SAC,
    Consumidor.gov e reclame aqui, o juíz não dá indenização por dano
    moral. Isso incentiva o consumidor a passar por todos os passos ao
    invés de ir direto ao judiciário.

A quinta reunião contou com a presença da diretoria de contencioso cível
do Grupo Pão de Açúcar.

1. Sobre ações coletivas e IRDR
  - Provavelmente não funciona pois a maioria dos processos estão nos
    JECs.
1. Sobre conciliação
  - A conciliação faz sentido e precisa ser incentivada.
  - A taxa de aceite à proposta de acordos é maior nos JECs.
1. Sobre incentivos para litigar
  - Problemas de vício de produto e entrega (logística) são as
    principais causas de pedir.
  - Juízes que incentivam ações judiciais através da aplicação de
    valores altos de indenização.
  - Existe banalização do dano moral.
  - Está ligado com os problemas da gratuidade
1. Sobre incentivos das empresas para cometerem ilícitos
  - O problema está geralmente com as fabricantes que não tomam
    responsabilidade e deixam a empresa no meio de campo.
  - As empresas enfrentam dificuldades no atendimento para devolver
    produtos e trocar itens com defeito.
  - Outra fonte externa aos esforços da empresa são problemas
    relacionados a cartões.
1. Sobre mecanismos de composição extrajudicial
  - É importante incentivar o contato direto com a companhia.
  - No entanto, os canais de atendimento atuais são ruins e não resolvem
    os problemas dos consumidores.
    
# Códigos para lidar com incorporações{#codpj}

\footnotesize

\begin{verbatim}
#as funções dessa parte do pacote
#são responsáveis por criar as colunas que serão
#efetivamente analisadas no relatório
arruma_sa <- function(string_vec){
  regex_sa_geral <- stringr::regex(
  "([^d][^e]) s *[\\./]?a *\\.?( [(].+[)])?@@@")
  string_vec_phase1 <- stringr::str_replace(
  string_vec, regex_sa_geral,"\\1 @s@a@\\2")
  regex_sa_particular <- regex("s/ *a|s\\.
  *a\\.?|( )sa@@@|( )+s ?a(@@@| )")
  string_vec_phase2 <- stringr::str_replace(
  string_vec_phase1, regex_sa_particular," @s@a@\\2")
  regex_estacio_de_sa <- regex('estacio de sa')
  string_vec_phase3 <- stringr::str_replace(
  string_vec_phase2, regex_estacio_de_sa,"estacio de @s@a@")
  return(stringr::str_trim(stringr::str_replace_all(
  string_vec_phase3, "[:space:]+", " ")))
}
arruma_ltda <- function(string_vec){
  regex_ltda_geral <- stringr::regex(
  "l[ \\.]*t[ \\.]*d[ \\.]*a")
  string_vec_phase1 <- stringr::str_replace(
  string_vec, regex_ltda_geral,"@l@t@d@a@")
  #regex_sa_particular <- regex("s/a")
  #string_vec_phase2 <- stringr::str_replace(string_vec_phase1,
  regex_sa_particular,"@l@t@d@a@")
  return(string_vec_phase1)
}
arruma_me <- function(string_vec){
  regex_me_geral <- stringr::regex(
  "([^de]) m *[\\./]?e *\\.?( [(].+[)])?@@@")
  string_vec_phase1 <- stringr::str_replace(
  string_vec, regex_me_geral,"\\1 @m@e@\\2")
  regex_me_particular <- regex("m/e")
  string_vec_phase2 <- stringr::str_replace(string_vec_phase1,
  regex_me_particular,"@m@e@")
  return(string_vec_phase2)
}
#'Fix column of brazillian company names
#'
#'This function receives a string vector of company names,
#'substitutes all types of "s/a" by "@s@a@",
#' all types of "ltda." by "@l@t@d@a"
#' and all types of "m.e." by "@m@e@".
#'At the end, it trims the vector,
#' replaces multiple spaces by one and removes accentuation
#'
#'@param names_column a string vector of company names
#'@return a better version of names_column
#'
#'@export
fix_nomes <- function(names_column){
  names_column %>%
    stringr::str_to_lower() %>%
    arruma_sa() %>%
    arruma_ltda() %>%
    arruma_me() %>%
    abjutils::rm_accent() %>%
    stringr::str_replace_all("[!#@@@%&'()*+,-./:;<=>?^_`{|}~.]",
    "")
}
vec2regex <- function(...){
  stringr::str_c(c(...), collapse = "|")
}
#' Collapes names of major companies
#'
#' In a vector of company names the same
#' company usually appears with various names.
#' This function lists some of them and
#' aggregates them under one main name.
#'
#' @param names_column a string vector of company names
#' @return the string vector with an
#' aggregation of the names of major companies
#'
#' @export
aggregate_major_companies <- function(names_column){
  lista_de_regex <- list(
    regex_claro = vec2regex("claro", "embratel", "bcp"),
    regex_rio_claro = vec2regex("rio claro"),
    regex_nextel = vec2regex("nextel"),
    #a telemar foi comprada pela oi em algum momento.
    regex_oi = vec2regex("telemar","( |^)oi( |@@@)", "tnl",
    "(brasil|br) ?teleco[mn]"),
    regex_itau = vec2regex("unibanco", "itau", "citicard"),
    regex_renner = vec2regex("banco a ?j renner"),
    regex_crefisa = vec2regex("crefisa"),
    regex_cdl_porto_alegre = vec2regex(
    "(cdl|camara( de)? dirigentes lojistas)"),
    regex_banco_credifibra = vec2regex("credifibra"),
    regex_farroupilha_consorcios = vec2regex("farroupilha"),
    regex_cacique = vec2regex("banco cacique"),
    regex_schahin = vec2regex("schahin"),
    regex_aymore = vec2regex("aymore"),
    regex_bradesco = vec2regex("bradesc"),
    regex_light = vec2regex("light","ligth"),
    regex_rio = vec2regex("estado do rio de janeiro"),
    regex_santander = vec2regex("santander"),
    regex_tim = vec2regex("tim"),
    regex_ampla = vec2regex("ampla"),
    regex_vvar = vec2regex("via varejo","vvar",
    "casa[s]? bahia", "globex"),
    regex_bmg = vec2regex("bmg"),
    regex_bb = vec2regex("banco do brasil", "bb"),
    regex_sky = vec2regex("sky"),
    regex_vivo = vec2regex("vivo", "telefonica",
    "telesp", 'gvt', 'global village teleco[mn]'),
    regex_ricardoeletro = vec2regex("ricardo ?eletro",
    "rn comercio"),
    regex_net = vec2regex("^net@@@", "^net ", " net ", " net@@@"),
    regex_panamericano = vec2regex("banco pan"),
    regex_cedae = vec2regex("cedae",
    "(cia[.]?|companhia) estadual de aguas"),
    regex_leader = vec2regex("leader"),
    regex_bv = vec2regex("bv financeira","^bv "),
    regex_amil = vec2regex("amil"),
    regex_lider = vec2regex("seguradora lider"),
    regex_cnova = vec2regex("cnova", "nova ?ponto ?com"),
    regex_samsung = vec2regex("samsung"),
    regex_tam = vec2regex("tam"),
    regex_lame = vec2regex("lojas americanas"),
    regex_ca = vec2regex("c&a"),
    regex_unimed = vec2regex("unimed"),
    regex_b2w = vec2regex("b2w"),
    regex_electrolux = vec2regex("ele[c]?trolux"),
    regex_citi = vec2regex("citibank"),
    regex_mrv = vec2regex("mrv"),
    regex_estacio_de_sa = vec2regex("estacio de sa"),
    regex_qualicorp = vec2regex("qualicorp"),
    regex_carrefour = vec2regex("carrefour"),
    regex_daycoval = vec2regex("daycoval"),
    regex_hsbc = vec2regex("hsbc"),
    regex_bonsucesso = vec2regex("bonsucesso"),
    regex_ibi = vec2regex("ibi"),
    regex_cruzeiro_do_sul = vec2regex("cruzeiro do sul"),
    regex_bgn = vec2regex("bgn"),
    regex_cielo = vec2regex("cielo"),
    regex_zurich = vec2regex("zurich"),
    regex_gol = vec2regex("vrg","gol"),
    regex_sony = vec2regex("sony"),
    regex_sendas = vec2regex("sendas"),
    regex_safra = vec2regex("safra"),
    regex_golden_cross = vec2regex("golden cross"),
    regex_banco_mercantil = vec2regex("banco mercantil"),
    regex_avista = vec2regex("avista"),
    regex_digibras = vec2regex("digibras"),
    regex_inss = vec2regex("inss",
    "instituto nacional do seguro social"),
    #coloquei um x aqui pra não pegar na regex de baixo
    regex_banco_vxolkswagen = vec2regex("banco volks[wv]age[nm]"),
    regex_volkswagen = vec2regex("volks[wv]age[nm]"),
    regex_energisa = vec2regex("energisa","cemat"),
    regex_secretaria_de_saude_mt = vec2regex(
    "estado de mato grosso secretaria (estadual|de estado) de saude"),
    regex_azul = vec2regex("azul linhas"),
    regex_serasa = vec2regex("serasa"),
    regex_spc = vec2regex("spc","scpc"),
    regex_porto_seguro = vec2regex("porto seguro"),
    regex_avon = vec2regex("avon"),
    regex_banco_finasa = vec2regex("finasa"),
    regex_natura = vec2regex("natura","rodobens"),
    regex_tokio_marine = vec2regex("tokio marine"),
    #coloquei um x em fxord pra não pegar na regex de baixo
    regex_banco_fxord = vec2regex("banco ford"),
    regex_ford = vec2regex("ford"),
    regex_basa = vec2regex("banco da amazonia","basa"),
    regex_pdg = vec2regex("pdg", "goldfarb"),
    regex_furnas = vec2regex("furnas"),
    regex_cef = vec2regex("cef","caixa economica federal","caixa"),
    regex_mapfre = vec2regex("mapfre"),
    regex_cvc = vec2regex("cvc"),
    #coloquei um x em fxiat pra não pegar na regex de baixo
    regex_banco_fxiat = vec2regex("banco fiat"),
    regex_ford = vec2regex("fiat"),
    regex_banco_hxonda = vec2regex("banco honda"),
    regex_honda = vec2regex("honda"),
    regex_catho = vec2regex("catho"),
    regex_buscape = vec2regex("buscape"),
    regex_abn = vec2regex("abn amro"),
    regex_riachuelo = vec2regex("riachuelo"),
    regex_banco_rural = vec2regex("banco rural"),
    regex_banco_gmac = vec2regex("banco gmac"),
    regex_renova = vec2regex("renova"),
    regex_modelo = vec2regex("supermercado modelo"),
    regex_philips = vec2regex("philips|phillips"),
    regex_positivo = vec2regex("positivo"),
    regex_lg = vec2regex("lg"),
    regex_lenovo = vec2regex("lenovo"),
    regex_magazine_luiza = vec2regex("magazine luiza"),
    regex_pernambucanas = vec2regex("pernambucanas"),
    regex_brastempo = vec2regex("brastemp"),
    regex_consul = vec2regex("consul"),
    regex_esmaltec = vec2regex("esmaltec"),
    regex_atlas = vec2regex("atlas"),
    regex_latina = vec2regex("latina"),
    regex_mueller = vec2regex("mueller"),
    regex_multiplus = vec2regex("multiplus"),
    regex_smiles = vec2regex("smiles"),
    regex_dotz = vec2regex("dotz"),
    regex_livelo = vec2regex("livelo"),
    regex_avianca = vec2regex("avianca"),
    regex_cab_cuiaba = vec2regex("cab cuiaba"),
    regex_losango = vec2regex("losango"),
    regex_novo_mundo_moveis_mt = vec2regex("novo ?mundo ?moveis"),
    regex_calcar = vec2regex("calcard"),
    regex_ativos = vec2regex("ativos"),
    regex_sanecap_mt = vec2regex("sanecap"),
    regex_prime_mt = vec2regex("prime incorporacoes"),
    regex_general_motors = vec2regex("general motors"),
    regex_lotufo_engenharia = vec2regex("lotufo"),
    regex_sulamerica = vec2regex("sul ?america"),
    regex_omni = vec2regex("omni financeira"),
    regex_brookfield_incorporadora = vec2regex("brookfield"),
    regex_banrisul = vec2regex("banrisul",
    "banco do estado do rio grande do sul"),
    regex_boa_vista = vec2regex("boa vista"),
    regex_ace = vec2regex("ace"),
    regex_aes_sul = vec2regex("aes sul"),
    regex_ceee = vec2regex("ceee",
    "companhia estadual de energia elétrica"),
    regex_cifra = vec2regex("cifra"),
    regex_corsan = vec2regex("corsan"),
    regex_rio_grande_energia = vec2regex("rio grande energia"),
    regex_sofisa = vec2regex("sofisa"),
    regex_cce = vec2regex("cce"))
colunas_bl <- purrr::map(lista_de_regex, str_detect,
string = names_column)
  for(i in seq_along(colunas_bl)){
    names_column <- ifelse(colunas_bl[[i]],
    names(colunas_bl)[i], names_column)
  }
  names_column
}

#' Creates column of companies segment
#'
#' Receives a vector of company names and return a vector os segments.
#'
#' @param names_column a string vector of company names
#' @return the string vector of company segments
#'
#' @export
market_segments <- function(names_column){
  lista_de_regex <- list(
    telecomunicacoes = vec2regex("vivo","oi","claro","tim","sky","net",
    "nextel"),
    bancos_cartoes_financeiras = vec2regex("losango","american
    express","amex","credicard","banco","ford","sofisa",
    "schahin","cacique","credifibra","farroupilha","aymore","cifra",
    "banco( |_)mercantil","herval","bonsucesso","bgn","citi",
    "gmac","abn",
    "daycoval","safra","cruzeiro( |_)do( |_)sul",
    "banrisul","volkswage[nm]","renner",
    "finasa","cef","itau","bb","bradesco","santander",
    "bmg","panamericano","bv","ourocard","hsbc"),
    comercio_eletronico = vec2regex("centaurocombr",
    "peixe urbano","cnova","kabum","nova pontocom","wmb",
    "buscape","submarino","americanascom",
    "casasbahiacom","pontofriocom","magazineluizacom"),
    banco_de_dados = vec2regex("spc","serasa","scpc",
    "boa( |_)vista","cdl"),
    fabricantes_eletrocnicos = vec2regex("cielo","sony",
    "samsung","lg","positivo",
    "philips","aoc","lenovo","semp toshipa","d-link","cce",
    "lexmark","compaq"),
    varejo = vec2regex("lame","magazine( |_)luiza",
    "vvar","ricardoeletro","pernambucanas",
    "sendas","riachuelo"),
    transporte_aereo = vec2regex("tam","latam","_azul",
    "gol","avianca","lufthansa"),
    seguros = vec2regex("segur","confianca","ace",
    "porto( |_)seguro","lider","mapfre","cardif","caixa segur",
    "bradesco auto","bb seguro auto","garantec","bradesco vida",
    "itau segur","assurant","zurich","luizaseg","sulamerica"),
    energia_gas_agua_esgoto = vec2regex("corsan",
    "rio( |_)grande( |_)energia","ceee","aes( |_)sul",
    "sanecap","cab( |_)cuiaba","furnas","cedae",
    "energisa","light","cpfl","(^| )rge( |@@@)",
    "copel","comgas","cagece",
    "coelce","ampla","fenosa","saae"),
    fabricantes_linha_branca = vec2regex("brastemp","consul",
    "electrolux","esmaltec",
    "atlas","latina","mueller"),
    agencias_de_viagem = vec2regex("decolar","viajanet","cvc"),
    programas_de_fidelidade = vec2regex("smiles","multiplus",
    "dotz","livelo"),
    planos_de_saude = vec2regex("amil","bradesco saude",
    "qualicorp","sulamerica odontologico",
    "sulamerica saude","odontoprev","unimed","golden cross"),
    recuperacao_credito = vec2regex("crefisa",
    "ibi","ativos","recovery"),
    perfumaria = vec2regex("natura","avon","boticario","eudora"),
    supermercados = vec2regex("extra","carrefour",
    "pao de acucar","walmart","big","hiper"),
    pagamento_eletronico = vec2regex("getnet","paypal",
    "pagseguro","ebanx","moip"))
  colunas_bl <- purrr::map(lista_de_regex, str_detect,
  string = names_column)
  for(i in seq_along(colunas_bl)){
    names_column <- ifelse(colunas_bl[[i]],
    names(colunas_bl)[i], names_column)
  }
  names_column

\end{verbatim}


# Códigos para filtrar pessoas físicas e jurídicas {#codpfpj}

O código abaixo é utilizado para filtrar as empresas. Esse é apenas o exemplo do TJRS. Outros códigos podem ser encontrados no pacote tidyML.

\begin{verbatim}
#' Filter only consumer lawsuits
#'
#' @param loaded_tjrs data_frame obtained from load_tjmt
#'
#' @export
filter_tjrs <- function(loaded_tjrs){
  d_tjrs <- loaded_tjrs %>%
    mutate(nome2 = tidyML::fix_nomes(reu) %>%
    tidyML::aggregate_major_companies())
  regex_empresa <- tidyML:::vec2regex("@s@a@","@l@t@d@a@",
  "estad","municip","secretari","@m@e@", "prefeit",
  "companhia","cidade","associacao","cooperativa",
  "regex","eireli","empresa","cia","banco","confederacao","servico",
  "advogados","sindicato","condominio","sociedade","camara","ministerio",
  "fazenda","hospital","universidade","associacao","edificio","cooperativa",
  "instituto","fundacao")
  d_tjrs <- d_tjrs %>%
    tidyr::separate(assunto, into = c('assunto_2',
    'assunto_pai'), remove = F, sep = "::") %>%
    mutate(assunto_final = ifelse(str_detect(assunto, "::"),
    assunto_2, assunto),
           assunto_final = stringr::str_trim(assunto_final),
           tem_pessoa = stringr::str_detect(nome2, regex_empresa)) %>%
    filter((assunto_final %in% stringr::str_trim(assuntos_consumeristas)),
    tem_pessoa)
  #especifico tjrs
  {especifico_tjrs <- c("Abatimento proporcional do preço",
  "Cadastro de Análise de Crédito",
  "Cobrança indevida de ligações ",
  "Cobrança Indevida de Serviços",
  "Comercialização de dados cadastrais de consumidores",
  "Contratos de Participacao Financeira",
  "Medicamento / Tratamento / Cirurgia de Eficácia não comprovada",
  "Metodologia de Reajuste de Tarifa - IRT",
  "Notificação",
  "Registro em Cadastro de Análise de Crédito",
  "Registro em Cadastro",
  "Registro em Cadastro de Inadimplentes",
  "Registro para comercialização de dados cadastrais de consumidores",
  "Reparação de Danos")}
  assuntos_consumeristas_estatiticos <- assuntos::class_automatica_abj %>%
    dplyr::filter(leaf != "")
  control_table <- tpur::control_table
  assuntos_consumeristas_tpu <- build_tpu_consumerista() %>%
    dplyr::filter(codigo != "")
  codigos_consumeristas <- unique(c(assuntos_consumeristas_estatiticos@@@leaf,
                                    assuntos_consumeristas_tpu@@@codigo))
  codigos_consumeristas_puros <- assuntos_consumeristas_tpu@@@codigo
  tpu <- tpur::download_table("assunto","estadual","1 grau") %>%
    tpur::build_table() %>%
    dplyr::filter(codigo != "") %>%
    dplyr::select(dplyr::contains("n"), codigo, cod_pai)
  l_tpu <- tpu %>%
    tidyr::gather(key, val, -codigo, -cod_pai) %>%
    dplyr::mutate(key = as.numeric(stringr::str_replace(key,"n",""))) %>%
    dplyr::group_by(codigo, cod_pai) %>%
    dplyr::summarise(val_node = val[max(key[val != ''])],
              val_pai = val[sort(key[val != ''])[sum(val != '')-1]]) %>%
    with(dplyr::data_frame(codigo = c(codigo, cod_pai),
                    assunto = c(val_node, val_pai))) %>%
    dplyr::distinct(codigo, assunto)
  assuntos_consumeristas <- l_tpu %>%
    dplyr::filter(codigo %in% codigos_consumeristas) %>%
    with(assunto) %>%
    c(especifico_tjrs) %>%
    unique
  assuntos_consumeristas_puros <- l_tpu %>%
    dplyr::filter(codigo %in% codigos_consumeristas_puros) %>%
    with(assunto) %>%
    c(especifico_tjrs) %>%
    unique
  base_filtrada <- d_tjrs %>%
    filter(assunto %in% assuntos_consumeristas, tipo_pessoa)
}

\end{verbatim}

