---
title: "Os Maiores Litigantes da Justiça Consumerista: Mapeamento e Proposições"
author: "Associação Brasileira de Jurimetria"
date: "`r format(Sys.Date(), '%d de %B de %Y')`"
#documentclass: report
bibliography: bibliography.bib
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
site: bookdown::bookdown_site
description: "Template de relatório da ABJ."
---

```{r setup, include = FALSE}
options(xtable.comment = FALSE)

knitr::opts_chunk$set(echo = F, message = F, comment = F, warning = F, fig.pos = 'H')
options(OutDec = ',')
```

```{r include_table, echo = F}
library(tidyverse)
library(stringr)

theme_set(theme(text = element_text(family = "sf")))

# include_table <- function(data_set, ...){
#   data_set %>%
#   xtable::xtable(...) %>%
#   print(tabular.environment = 'longtable', comment = F,
#           floating = FALSE, include.rownames = F)
# }

regex2coolname <- function(rgx){
  rgx %>% 
    stringr::str_replace_all("regex_","") %>% 
    stringr::str_replace_all("([:space:]|_)+"," ") %>% 
    stringr::str_to_title()
}

fix_labels_2 <- function(nome2){
  case_when(
    nome2 == "regex_oi" ~ "Oi Telecomunicações",
    nome2 == "regex_serasa" ~ "Serasa Experian",
    nome2 == "regex_itau" ~ "Itaú",
    nome2 == "regex_boa_vista" ~ "Boa Vista SPC",
    nome2 == "regex_bradesco" ~ "Bradesco",
    nome2 == "regex_claro" ~ "Claro",
    nome2 == "regex_bv" ~ "Banco Votorantim",
    nome2 == "regex_cdl_porto_alegre" ~ "CDL Porto Alegre",
    nome2 == "regex_vivo" ~ "Vivo",
    nome2 == "regex_santander" ~ "Santander",
    nome2 == "regex_bb" ~ "Banco do Brasil",
    nome2 == "regex_banrisul" ~ "Banrisul",
    nome2 == "regex_ceee" ~ "Companhia de Estadual de Energia Elétrica",
    nome2 == "regex_rio_grande_energia" ~ "Rio Grande Energia",
    nome2 == "regex_aes_sul" ~ "AES Sul",
    nome2 == "regex_panamericano" ~ "Banco Pan",
    nome2 == "regex_tim" ~ "Tim",
    nome2 == "regex_unimed" ~ "Unimed",
    nome2 == "regex_banco_finasa" ~ "Banco Finasa",
    nome2 == "regex_porto_seguro" ~ "Porto Seguro",
    nome2 == "bancos_cartoes_financeiras" ~ "Instituições Financeiras",
    nome2 == "telecomunicacoes" ~ "Telecomunicações",
    nome2 == "banco_de_dados" ~ "Administradoras de cadastro de inadimplentes",
    nome2 == "energia_gas_agua_esgoto" ~ "Concessionárias de serviços básicos",
    nome2 == "seguros" ~ "Companhias de seguro",
    nome2 == "planos_de_saude" ~ "Planos de Saúde",
    nome2 == "transporte_aereo" ~ "Transporte Aéreo",
    nome2 == "supermercados" ~ "Supermercados",
    nome2 == "fabricantes_eletrocnicos" ~ "Fabricantes Eletrônicos",
    nome2 == "varejo" ~ "Varejo",
    nome2 == "recuperacao_credito" ~ "Companhias de recuperação de crédito",
    nome2 == "fabricantes_linha_branca" ~ "Fabricantes de eletrodomésticos da linha branca",
    nome2 == "nobre seguradora do brasil @s@a@" ~ "Nobre Seguradora",
    nome2 == "hdi seguros @s@a@" ~ "HDI Seguros",
    nome2 == "liberty seguros @s@a@" ~ "Liberty Seguros",
    nome2 == "federal seguros @s@a@" ~ "Federal Seguros",
    nome2 == "b v financeira @s@a@  credito financiamento e investimento" ~ "BV Financeira",
    nome2 == "nobre seguradora do brasil @s@a@" ~ "Nobre Seguradoda do Brasil",
    nome2 == "hdi seguros @s@a@" ~ "HDI Seguros",
    nome2 == "liberty seguros @s@a@" ~ "Liberty Seguros",
    nome2 == "hipercard banco multiplo @s@a@" ~ "Hipercard",
    nome2 == "federal seguros @s@a@" ~ "Federal Seguros",
    nome2 == "b v financeira @s@a@ credito financiamento e investimento" ~ "Banco Votorantim",
    nome2 == "planserv assistencia a saude dos servidores publicos estaduais" ~ "Planserv",
    TRUE ~ regex2coolname(nome2)
  )
}

fix_labels <- function(nome2){
  fix_labels_2(nome2) %>% 
  stringr::str_wrap(width = 15)
}

add_hline_before_rowsum <- function(xtable_lines){
  
  new_lines <- character(length(xtable_lines))
  
  line_with_totals <- stringr::str_which(xtable_lines, "Total")
  
  if(length(line_with_totals) == 0){
    return(xtable_lines)
  }
  
  new_lines[1:line_with_totals] <- c(xtable_lines[1:(line_with_totals-1)], "\\hline")
  new_lines[line_with_totals+1] <- xtable_lines[line_with_totals]
  new_lines[(line_with_totals+2):length(xtable_lines)] <- xtable_lines[(line_with_totals+2):length(xtable_lines)]
  
  return(new_lines)
}

remove_double_hline <- function(xtable_lines){
  stringr::str_replace_all(xtable_lines, stringr::fixed('\\hline\n\\hline\n'), '\\hline\n')
}

#bold <- function(x) {paste('{\\textbf{',x,'}}', sep ='')}
if(knitr:::is_latex_output()){
  knit_print.data.frame = function(x, ...) {
  
    maybe_mutate_at <- purrr::possibly(function(d, coluna, ...){
      mutate_at(d, .vars = coluna, ...)
    }, otherwise = x)
    
    d <- x %>% 
    maybe_mutate_at(coluna = 'nome2', fix_labels)
    
     maybe_mutate_at <- purrr::possibly(function(d, coluna, ...){
      mutate_at(d, .vars = coluna, ...)
    }, otherwise = d)
    
    d <- d %>% 
    maybe_mutate_at(coluna = 'area', fix_labels)
    
    maybe_mutate_at <- purrr::possibly(function(d, coluna, ...){
      mutate_at(d, .vars = coluna, ...)
    }, otherwise = d)
    
    d <- d %>% 
    maybe_mutate_at(coluna = 'nome_fantasia', fix_labels)
    
    nomes <- names(d)
    
    names(d) <- case_when(
      nomes == "n" ~ "Frequência",
      nomes == "p" ~ "Percentual", 
      nomes == "p_acum" ~ "Percentual Acumulado",
      nomes == "nome2" ~ "Nome da Empresa ou Grupo",
      nomes == "assunto_final" ~ "Causa de pedir (Assunto)",
      nomes == "assunto_nome" ~ "Causa de pedir (Assunto)",
      nomes == "descricao" ~ "Descrição",
      nomes == "nome_fantasia" ~ "Nome da Empresa ou Grupo",
      TRUE ~ stringr::str_to_title(nomes)
    )
  
      res <- capture.output(d %>% 
          xtable::xtable(..., label = knitr::opts_current$get("label")) %>% 
          print(tabular.environment = 'longtable', comment = F,
          floating = FALSE,
          #sanitize.colnames.function=bold,
          include.rownames = F, caption.placement = 'top'))
    
      res %>% 
        add_hline_before_rowsum() %>%
        paste0(collapse = '\n') %>%
        remove_double_hline() %>% 
        knitr::asis_output()
  }
  options(knitr.table.format = 'markdown')
} else {
  knit_print.data.frame = knitr::kable
  options(knitr.table.format = 'pandoc')
}
```

